[package]
name = "google-fonts-heatmap"
version = "0.1.0"
edition = "2021"

[lib]
name = "google_fonts_heatmap_rust"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.27.1"
pyo3 = { version = "0.27.0", features = ["extension-module"] }
skrifa = "0.39.0"
